[package]
name = "board_plugin"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = ["colored"]

[dependencies]
bevy = "0.10.1"
bevy-inspector-egui = { version = "0.18.3", optional = false }
colored = { version = "2.0.0", optional = true }
rand = "0.8.5"
serde = "1.0.159"
